### PR TITLE
Added new parameter to enable/disable the white dots on surface

### PR DESCRIPTION
**Pull request by BrutalCoding**
Added the ability to disable or enable the plane renderer (white dots) when it detects surfaces

The ArCoreView() now has a new property named "enablePlaneRenderer", by default its turned on which means you'll see the white dots.

### CODE REVIEW

**Comment by AlinaStepanova** [comment]
Hi @BrutalCoding, @giandifra!

I am trying to use this feature but still the white dots are shown.
The way I am using it:
```
ArCoreView(
    onArCoreViewCreated: _onArCoreViewCreated,
    type: ArCoreViewType.AUGMENTEDIMAGES,
    enablePlaneRenderer: false,
)
```
Device: Pixel 4, android version: 11
Could you please help in resolving this issue?
dots

**Comment by BrutalCoding** [comment]
Hi @AlinaStepanova,

I’ll see if I can replicate this issue during the weekend and if so, will attempt to fix it. From reading your code it seems you do nothing wrong.

**Comment by AlinaStepanova** [comment]
@BrutalCoding thank you

**Comment by giandifra** [comment]
@BrutalCoding  @AlinaStepanova  Have you this in new transformable_node branch? You can see more here #89

**Comment by BrutalCoding** [comment]
Had little time this weekend and couldn’t find the issue at first glance🤔. I’ll try again within a few days.

**Comment by AlinaStepanova** [comment]
As a temporary solution, I used this line of code in the ArCoreAugmentedImagesView class:

`config?.planeFindingMode = Config.PlaneFindingMode.DISABLED`

https://developers.google.com/ar/reference/java/com/google/ar/core/Config.PlaneFindingMode

**Comment by MarkAlexanderDev** [comment]
Thanks @AlinaStepanova! I've implemented it and the performances are also 10 times better

**Pull request merged**
