### PR TITLE
Updated AR core, sceneform, compile SDK and AGP versions 

### PR DESCRIPTION
**Pull request by Haris2v**
Updated Kotlin version from 1.3.50 to 1.6.0
Update AGP version from 6.7 to 7.3
Updated target SDK version from 31 to 33
Updated AR core Android SDK version from 1.13.0 to 1.38.0
updated AR sceneform:core dependencies to latest version
Fixed null check issue in the ArCoreView.kt

### CODE REVIEW

**Review by KanmaChizea — APPROVED** [review]

**Review by FerdiHr — APPROVED** [review]

**Comment by FerdiHr** [comment]
Hey @giandifra possible to check and if okay to release a new version ? Would love to use the AR inside my app !

**Comment by giandifra** [comment]
> Hey @giandifra possible to check and if okay to release a new version ? Would love to use the AR inside my app !

Hello, can you try this branch? 

https://github.com/giandifra/arcore_flutter_plugin/tree/android-upgrading

**Comment by FerdiHr** [comment]
Hey thanks for the branch ! 
I still have an error 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkInternalDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class android.support.v4.app.INotificationSideChannel found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.app.INotificationSideChannel$Stub found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.app.INotificationSideChannel$Stub$Proxy found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.os.IResultReceiver found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.os.IResultReceiver$Stub found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.os.IResultReceiver$Stub$Proxy found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.os.ResultReceiver found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.os.ResultReceiver$1 found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.os.ResultReceiver$MyResultReceiver found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)
     Duplicate class android.support.v4.os.ResultReceiver$MyRunnable found in modules core-1.13.0-alpha01-runtime (androidx.core:core:1.13.0-alpha01) and support-compat-27.1.0-runtime (com.android.support:support-compat:27.1.0)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

Does it ring a bell ?

**Review by mklimko-perpetio — APPROVED** [review]

**Comment by giandifra** [comment]
The upgrades has done from this [PR](https://github.com/giandifra/arcore_flutter_plugin/pull/228)

**Pull request closed without merging**
